/**
 * Lookup tables for TeX commands
 * Port of Text.TeXMath.Readers.TeX.Commands from Haskell
 */

import type { Exp, TextType } from './types';

export const styleOps: Record<string, (exps: Exp[]) => Exp> = {
  '\\mathrm': (exps) => ({ type: 'EStyled', textType: 'TextNormal', value: exps }),
  '\\mathup': (exps) => ({ type: 'EStyled', textType: 'TextNormal', value: exps }),
  '\\mathbf': (exps) => ({ type: 'EStyled', textType: 'TextNormal', value: [{ type: 'EStyled', textType: 'TextBold', value: exps }] }),
  '\\boldsymbol': (exps) => ({ type: 'EStyled', textType: 'TextBold', value: exps }),
  '\\bm': (exps) => ({ type: 'EStyled', textType: 'TextBold', value: exps }),
  '\\symbf': (exps) => ({ type: 'EStyled', textType: 'TextBold', value: exps }),
  '\\mathbold': (exps) => ({ type: 'EStyled', textType: 'TextBold', value: exps }),
  '\\pmb': (exps) => ({ type: 'EStyled', textType: 'TextBold', value: exps }),
  '\\mathbfup': (exps) => ({ type: 'EStyled', textType: 'TextBold', value: exps }),
  '\\mathit': (exps) => ({ type: 'EStyled', textType: 'TextItalic', value: exps }),
  '\\mathtt': (exps) => ({ type: 'EStyled', textType: 'TextMonospace', value: exps }),
  '\\texttt': (exps) => ({ type: 'EStyled', textType: 'TextMonospace', value: exps }),
  '\\mathsf': (exps) => ({ type: 'EStyled', textType: 'TextSansSerif', value: exps }),
  '\\mathsfup': (exps) => ({ type: 'EStyled', textType: 'TextSansSerif', value: exps }),
  '\\mathbb': (exps) => ({ type: 'EStyled', textType: 'TextDoubleStruck', value: exps }),
  '\\mathds': (exps) => ({ type: 'EStyled', textType: 'TextDoubleStruck', value: exps }),
  '\\mathcal': (exps) => ({ type: 'EStyled', textType: 'TextScript', value: exps }),
  '\\mathscr': (exps) => ({ type: 'EStyled', textType: 'TextScript', value: exps }),
  '\\mathfrak': (exps) => ({ type: 'EStyled', textType: 'TextFraktur', value: exps }),
  '\\mathbfit': (exps) => ({ type: 'EStyled', textType: 'TextBoldItalic', value: exps }),
  '\\mathbfsfup': (exps) => ({ type: 'EStyled', textType: 'TextSansSerifBold', value: exps }),
  '\\mathbfsfit': (exps) => ({ type: 'EStyled', textType: 'TextSansSerifBoldItalic', value: exps }),
  '\\mathbfscr': (exps) => ({ type: 'EStyled', textType: 'TextBoldScript', value: exps }),
  '\\mathbffrak': (exps) => ({ type: 'EStyled', textType: 'TextBoldFraktur', value: exps }),
  '\\mathbfcal': (exps) => ({ type: 'EStyled', textType: 'TextBoldScript', value: exps }),
  '\\mathsfit': (exps) => ({ type: 'EStyled', textType: 'TextSansSerifItalic', value: exps }),
};

export const textOps: Record<string, (text: string) => Exp> = {
  '\\textrm': (text) => ({ type: 'EText', textType: 'TextNormal', value: text }),
  '\\text': (text) => ({ type: 'EText', textType: 'TextNormal', value: text }),
  '\\textbf': (text) => ({ type: 'EText', textType: 'TextBold', value: text }),
  '\\textit': (text) => ({ type: 'EText', textType: 'TextItalic', value: text }),
  '\\texttt': (text) => ({ type: 'EText', textType: 'TextMonospace', value: text }),
  '\\textsf': (text) => ({ type: 'EText', textType: 'TextSansSerif', value: text }),
  '\\mbox': (text) => ({ type: 'EText', textType: 'TextNormal', value: text }),
};

export const enclosures: Record<string, Exp> = {
  '(': { type: 'ESymbol', symbolType: 'Open', value: '(' },
  ')': { type: 'ESymbol', symbolType: 'Close', value: ')' },
  '[': { type: 'ESymbol', symbolType: 'Open', value: '[' },
  ']': { type: 'ESymbol', symbolType: 'Close', value: ']' },
  '\\{': { type: 'ESymbol', symbolType: 'Open', value: '{' },
  '\\}': { type: 'ESymbol', symbolType: 'Close', value: '}' },
  '\\lbrack': { type: 'ESymbol', symbolType: 'Open', value: '[' },
  '\\lbrace': { type: 'ESymbol', symbolType: 'Open', value: '{' },
  '\\rbrack': { type: 'ESymbol', symbolType: 'Close', value: ']' },
  '\\rbrace': { type: 'ESymbol', symbolType: 'Close', value: '}' },
  '\\langle': { type: 'ESymbol', symbolType: 'Open', value: '\u27E8' },
  '\\rangle': { type: 'ESymbol', symbolType: 'Close', value: '\u27E9' },
  '\\lfloor': { type: 'ESymbol', symbolType: 'Open', value: '\u230A' },
  '\\rfloor': { type: 'ESymbol', symbolType: 'Close', value: '\u230B' },
  '\\lceil': { type: 'ESymbol', symbolType: 'Open', value: '\u2308' },
  '\\rceil': { type: 'ESymbol', symbolType: 'Close', value: '\u2309' },
  '|': { type: 'ESymbol', symbolType: 'Close', value: '|' },
  '\\|': { type: 'ESymbol', symbolType: 'Open', value: '\u2225' },
  '\\lvert': { type: 'ESymbol', symbolType: 'Open', value: '\u007C' },
  '\\rvert': { type: 'ESymbol', symbolType: 'Close', value: '\u007C' },
  '\\vert': { type: 'ESymbol', symbolType: 'Close', value: '\u007C' },
  '\\lVert': { type: 'ESymbol', symbolType: 'Open', value: '\u2225' },
  '\\rVert': { type: 'ESymbol', symbolType: 'Close', value: '\u2225' },
  '\\Vert': { type: 'ESymbol', symbolType: 'Close', value: '\u2016' },
};

export const operators: Record<string, Exp> = {
  '+': { type: 'ESymbol', symbolType: 'Bin', value: '+' },
  '-': { type: 'ESymbol', symbolType: 'Bin', value: '\u2212' },
  '*': { type: 'ESymbol', symbolType: 'Bin', value: '*' },
  '@': { type: 'ESymbol', symbolType: 'Ord', value: '@' },
  ',': { type: 'ESymbol', symbolType: 'Pun', value: ',' },
  '.': { type: 'ESymbol', symbolType: 'Ord', value: '.' },
  ';': { type: 'ESymbol', symbolType: 'Pun', value: ';' },
  ':': { type: 'ESymbol', symbolType: 'Rel', value: ':' },
  '?': { type: 'ESymbol', symbolType: 'Ord', value: '?' },
  '>': { type: 'ESymbol', symbolType: 'Rel', value: '>' },
  '<': { type: 'ESymbol', symbolType: 'Rel', value: '<' },
  '!': { type: 'ESymbol', symbolType: 'Ord', value: '!' },
  "'": { type: 'ESymbol', symbolType: 'Ord', value: '\u2032' },
  "''": { type: 'ESymbol', symbolType: 'Ord', value: '\u2033' },
  "'''": { type: 'ESymbol', symbolType: 'Ord', value: '\u2034' },
  "''''": { type: 'ESymbol', symbolType: 'Ord', value: '\u2057' },
  '=': { type: 'ESymbol', symbolType: 'Rel', value: '=' },
  ':=': { type: 'ESymbol', symbolType: 'Rel', value: ':=' },
  '/': { type: 'ESymbol', symbolType: 'Ord', value: '/' },
  '~': { type: 'ESpace', width: 4/18 },
};

// Comprehensive symbol table - core math symbols
export const symbols: Record<string, Exp> = {
  '\\\n': { type: 'ESpace', width: 2/9 },
  '\\ ': { type: 'ESpace', width: 2/9 },
  '\\!': { type: 'ESpace', width: -1/6 },
  '\\,': { type: 'ESpace', width: 1/6 },
  '\\:': { type: 'ESpace', width: 2/9 },
  '\\;': { type: 'ESpace', width: 5/18 },
  '\\>': { type: 'ESpace', width: 2/9 },
  '\\quad': { type: 'ESpace', width: 1 },
  '\\qquad': { type: 'ESpace', width: 2 },
  
  // Greek letters
  '\\alpha': { type: 'EIdentifier', value: '\u03B1' },
  '\\beta': { type: 'EIdentifier', value: '\u03B2' },
  '\\gamma': { type: 'EIdentifier', value: '\u03B3' },
  '\\delta': { type: 'EIdentifier', value: '\u03B4' },
  '\\epsilon': { type: 'EIdentifier', value: '\u03F5' },
  '\\varepsilon': { type: 'EIdentifier', value: '\u03B5' },
  '\\zeta': { type: 'EIdentifier', value: '\u03B6' },
  '\\eta': { type: 'EIdentifier', value: '\u03B7' },
  '\\theta': { type: 'EIdentifier', value: '\u03B8' },
  '\\vartheta': { type: 'EIdentifier', value: '\u03D1' },
  '\\iota': { type: 'EIdentifier', value: '\u03B9' },
  '\\kappa': { type: 'EIdentifier', value: '\u03BA' },
  '\\lambda': { type: 'EIdentifier', value: '\u03BB' },
  '\\mu': { type: 'EIdentifier', value: '\u03BC' },
  '\\nu': { type: 'EIdentifier', value: '\u03BD' },
  '\\xi': { type: 'EIdentifier', value: '\u03BE' },
  '\\pi': { type: 'EIdentifier', value: '\u03C0' },
  '\\rho': { type: 'EIdentifier', value: '\u03C1' },
  '\\sigma': { type: 'EIdentifier', value: '\u03C3' },
  '\\tau': { type: 'EIdentifier', value: '\u03C4' },
  '\\upsilon': { type: 'EIdentifier', value: '\u03C5' },
  '\\phi': { type: 'EIdentifier', value: '\u03D5' },
  '\\varphi': { type: 'EIdentifier', value: '\u03C6' },
  '\\chi': { type: 'EIdentifier', value: '\u03C7' },
  '\\psi': { type: 'EIdentifier', value: '\u03C8' },
  '\\omega': { type: 'EIdentifier', value: '\u03C9' },
  
  // Capital Greek letters
  '\\Gamma': { type: 'EIdentifier', value: '\u0393' },
  '\\Delta': { type: 'EIdentifier', value: '\u0394' },
  '\\Theta': { type: 'EIdentifier', value: '\u0398' },
  '\\Lambda': { type: 'EIdentifier', value: '\u039B' },
  '\\Xi': { type: 'EIdentifier', value: '\u039E' },
  '\\Pi': { type: 'EIdentifier', value: '\u03A0' },
  '\\Sigma': { type: 'EIdentifier', value: '\u03A3' },
  '\\Upsilon': { type: 'EIdentifier', value: '\u03A5' },
  '\\Phi': { type: 'EIdentifier', value: '\u03A6' },
  '\\Psi': { type: 'EIdentifier', value: '\u03A8' },
  '\\Omega': { type: 'EIdentifier', value: '\u03A9' },
  
  // Math operators
  '\\sin': { type: 'EMathOperator', value: 'sin' },
  '\\cos': { type: 'EMathOperator', value: 'cos' },
  '\\tan': { type: 'EMathOperator', value: 'tan' },
  '\\cot': { type: 'EMathOperator', value: 'cot' },
  '\\sec': { type: 'EMathOperator', value: 'sec' },
  '\\csc': { type: 'EMathOperator', value: 'csc' },
  '\\sinh': { type: 'EMathOperator', value: 'sinh' },
  '\\cosh': { type: 'EMathOperator', value: 'cosh' },
  '\\tanh': { type: 'EMathOperator', value: 'tanh' },
  '\\coth': { type: 'EMathOperator', value: 'coth' },
  '\\arcsin': { type: 'EMathOperator', value: 'arcsin' },
  '\\arccos': { type: 'EMathOperator', value: 'arccos' },
  '\\arctan': { type: 'EMathOperator', value: 'arctan' },
  '\\arg': { type: 'EMathOperator', value: 'arg' },
  '\\log': { type: 'EMathOperator', value: 'log' },
  '\\ln': { type: 'EMathOperator', value: 'ln' },
  '\\lg': { type: 'EMathOperator', value: 'lg' },
  '\\exp': { type: 'EMathOperator', value: 'exp' },
  '\\det': { type: 'EMathOperator', value: 'det' },
  '\\dim': { type: 'EMathOperator', value: 'dim' },
  '\\gcd': { type: 'EMathOperator', value: 'gcd' },
  '\\hom': { type: 'EMathOperator', value: 'hom' },
  '\\ker': { type: 'EMathOperator', value: 'ker' },
  '\\lim': { type: 'EMathOperator', value: 'lim' },
  '\\limsup': { type: 'EMathOperator', value: 'limsup' },
  '\\liminf': { type: 'EMathOperator', value: 'liminf' },
  '\\max': { type: 'EMathOperator', value: 'max' },
  '\\min': { type: 'EMathOperator', value: 'min' },
  '\\sup': { type: 'EMathOperator', value: 'sup' },
  '\\inf': { type: 'EMathOperator', value: 'inf' },
  '\\Pr': { type: 'EMathOperator', value: 'Pr' },
  
  // Binary operators and relations
  '\\pm': { type: 'ESymbol', symbolType: 'Bin', value: '\u00B1' },
  '\\mp': { type: 'ESymbol', symbolType: 'Bin', value: '\u2213' },
  '\\times': { type: 'ESymbol', symbolType: 'Bin', value: '\u00D7' },
  '\\div': { type: 'ESymbol', symbolType: 'Bin', value: '\u00F7' },
  '\\cdot': { type: 'ESymbol', symbolType: 'Bin', value: '\u22C5' },
  '\\ast': { type: 'ESymbol', symbolType: 'Bin', value: '*' },
  '\\star': { type: 'ESymbol', symbolType: 'Bin', value: '\u22C6' },
  '\\circ': { type: 'ESymbol', symbolType: 'Bin', value: '\u2218' },
  '\\bullet': { type: 'ESymbol', symbolType: 'Bin', value: '\u2022' },
  '\\cap': { type: 'ESymbol', symbolType: 'Bin', value: '\u2229' },
  '\\cup': { type: 'ESymbol', symbolType: 'Bin', value: '\u222A' },
  '\\vee': { type: 'ESymbol', symbolType: 'Bin', value: '\u2228' },
  '\\wedge': { type: 'ESymbol', symbolType: 'Bin', value: '\u2227' },
  '\\oplus': { type: 'ESymbol', symbolType: 'Bin', value: '\u2295' },
  '\\ominus': { type: 'ESymbol', symbolType: 'Bin', value: '\u2296' },
  '\\otimes': { type: 'ESymbol', symbolType: 'Bin', value: '\u2297' },
  '\\oslash': { type: 'ESymbol', symbolType: 'Bin', value: '\u2298' },
  '\\odot': { type: 'ESymbol', symbolType: 'Bin', value: '\u2299' },
  '\\setminus': { type: 'ESymbol', symbolType: 'Bin', value: '\\' },
  '\\backslash': { type: 'ESymbol', symbolType: 'Bin', value: '\u2216' },
  
  // Relations
  '\\leq': { type: 'ESymbol', symbolType: 'Rel', value: '\u2264' },
  '\\geq': { type: 'ESymbol', symbolType: 'Rel', value: '\u2265' },
  '\\le': { type: 'ESymbol', symbolType: 'Rel', value: '\u2264' },
  '\\ge': { type: 'ESymbol', symbolType: 'Rel', value: '\u2265' },
  '\\ll': { type: 'ESymbol', symbolType: 'Rel', value: '\u226A' },
  '\\gg': { type: 'ESymbol', symbolType: 'Rel', value: '\u226B' },
  '\\neq': { type: 'ESymbol', symbolType: 'Rel', value: '\u2260' },
  '\\ne': { type: 'ESymbol', symbolType: 'Rel', value: '\u2260' },
  '\\equiv': { type: 'ESymbol', symbolType: 'Rel', value: '\u2261' },
  '\\sim': { type: 'ESymbol', symbolType: 'Rel', value: '\u223C' },
  '\\simeq': { type: 'ESymbol', symbolType: 'Rel', value: '\u2243' },
  '\\approx': { type: 'ESymbol', symbolType: 'Rel', value: '\u2248' },
  '\\cong': { type: 'ESymbol', symbolType: 'Rel', value: '\u2245' },
  '\\propto': { type: 'ESymbol', symbolType: 'Rel', value: '\u221D' },
  '\\prec': { type: 'ESymbol', symbolType: 'Rel', value: '\u227A' },
  '\\succ': { type: 'ESymbol', symbolType: 'Rel', value: '\u227B' },
  '\\preceq': { type: 'ESymbol', symbolType: 'Rel', value: '\u2AAF' },
  '\\succeq': { type: 'ESymbol', symbolType: 'Rel', value: '\u2AB0' },
  '\\subset': { type: 'ESymbol', symbolType: 'Rel', value: '\u2282' },
  '\\supset': { type: 'ESymbol', symbolType: 'Rel', value: '\u2283' },
  '\\subseteq': { type: 'ESymbol', symbolType: 'Rel', value: '\u2286' },
  '\\supseteq': { type: 'ESymbol', symbolType: 'Rel', value: '\u2287' },
  '\\in': { type: 'ESymbol', symbolType: 'Rel', value: '\u2208' },
  '\\ni': { type: 'ESymbol', symbolType: 'Rel', value: '\u220B' },
  '\\notin': { type: 'ESymbol', symbolType: 'Rel', value: '\u2209' },
  '\\perp': { type: 'ESymbol', symbolType: 'Rel', value: '\u22A5' },
  '\\parallel': { type: 'ESymbol', symbolType: 'Rel', value: '\u2225' },
  '\\mid': { type: 'ESymbol', symbolType: 'Rel', value: '\u2223' },
  
  // Arrows
  '\\leftarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u2190' },
  '\\rightarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u2192' },
  '\\leftrightarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u2194' },
  '\\Leftarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u21D0' },
  '\\Rightarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u21D2' },
  '\\Leftrightarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u21D4' },
  '\\uparrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u2191' },
  '\\downarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u2193' },
  '\\updownarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u2195' },
  '\\Uparrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u21D1' },
  '\\Downarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u21D3' },
  '\\Updownarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u21D5' },
  '\\mapsto': { type: 'ESymbol', symbolType: 'Rel', value: '\u21A6' },
  '\\longmapsto': { type: 'ESymbol', symbolType: 'Rel', value: '\u27FC' },
  '\\longleftarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u27F5' },
  '\\longrightarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u27F6' },
  '\\longleftrightarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u27F7' },
  '\\Longleftarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u27F8' },
  '\\Longrightarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u27F9' },
  '\\Longleftrightarrow': { type: 'ESymbol', symbolType: 'Rel', value: '\u27FA' },
  '\\iff': { type: 'ESymbol', symbolType: 'Rel', value: '\u21D4' },
  '\\to': { type: 'ESymbol', symbolType: 'Rel', value: '\u2192' },
  
  // Large operators
  '\\sum': { type: 'ESymbol', symbolType: 'Op', value: '\u2211' },
  '\\prod': { type: 'ESymbol', symbolType: 'Op', value: '\u220F' },
  '\\coprod': { type: 'ESymbol', symbolType: 'Op', value: '\u2210' },
  '\\int': { type: 'ESymbol', symbolType: 'Op', value: '\u222B' },
  '\\iint': { type: 'ESymbol', symbolType: 'Op', value: '\u222C' },
  '\\iiint': { type: 'ESymbol', symbolType: 'Op', value: '\u222D' },
  '\\oint': { type: 'ESymbol', symbolType: 'Op', value: '\u222E' },
  '\\bigcup': { type: 'ESymbol', symbolType: 'Op', value: '\u22C3' },
  '\\bigcap': { type: 'ESymbol', symbolType: 'Op', value: '\u22C2' },
  '\\bigvee': { type: 'ESymbol', symbolType: 'Op', value: '\u22C1' },
  '\\bigwedge': { type: 'ESymbol', symbolType: 'Op', value: '\u22C0' },
  '\\biguplus': { type: 'ESymbol', symbolType: 'Op', value: '\u2A04' },
  '\\bigoplus': { type: 'ESymbol', symbolType: 'Op', value: '\u2A01' },
  '\\bigotimes': { type: 'ESymbol', symbolType: 'Op', value: '\u2A02' },
  '\\bigodot': { type: 'ESymbol', symbolType: 'Op', value: '\u2A00' },
  
  // Misc symbols
  '\\infty': { type: 'ESymbol', symbolType: 'Ord', value: '\u221E' },
  '\\partial': { type: 'ESymbol', symbolType: 'Ord', value: '\u2202' },
  '\\nabla': { type: 'ESymbol', symbolType: 'Ord', value: '\u2207' },
  '\\forall': { type: 'ESymbol', symbolType: 'Op', value: '\u2200' },
  '\\exists': { type: 'ESymbol', symbolType: 'Op', value: '\u2203' },
  '\\neg': { type: 'ESymbol', symbolType: 'Op', value: '\u00AC' },
  '\\lnot': { type: 'ESymbol', symbolType: 'Op', value: '\u00AC' },
  '\\emptyset': { type: 'ESymbol', symbolType: 'Ord', value: '\u2205' },
  '\\varnothing': { type: 'ESymbol', symbolType: 'Ord', value: '\u2205' },
  '\\aleph': { type: 'ESymbol', symbolType: 'Ord', value: '\u2135' },
  '\\ell': { type: 'ESymbol', symbolType: 'Ord', value: '\u2113' },
  '\\hbar': { type: 'ESymbol', symbolType: 'Ord', value: '\u210F' },
  '\\wp': { type: 'ESymbol', symbolType: 'Ord', value: '\u2118' },
  '\\Re': { type: 'ESymbol', symbolType: 'Ord', value: '\u211C' },
  '\\Im': { type: 'ESymbol', symbolType: 'Ord', value: '\u2111' },
  '\\angle': { type: 'ESymbol', symbolType: 'Ord', value: '\u2220' },
  '\\triangle': { type: 'ESymbol', symbolType: 'Ord', value: '\u25B3' },
  '\\square': { type: 'ESymbol', symbolType: 'Ord', value: '\u25A1' },
  '\\diamond': { type: 'ESymbol', symbolType: 'Op', value: '\u22C4' },
  '\\flat': { type: 'ESymbol', symbolType: 'Ord', value: '\u266D' },
  '\\natural': { type: 'ESymbol', symbolType: 'Ord', value: '\u266E' },
  '\\sharp': { type: 'ESymbol', symbolType: 'Ord', value: '\u266F' },
  '\\dots': { type: 'ESymbol', symbolType: 'Ord', value: '\u2026' },
  '\\ldots': { type: 'ESymbol', symbolType: 'Ord', value: '\u2026' },
  '\\cdots': { type: 'ESymbol', symbolType: 'Ord', value: '\u22EF' },
  '\\vdots': { type: 'ESymbol', symbolType: 'Ord', value: '\u22EE' },
  '\\ddots': { type: 'ESymbol', symbolType: 'Ord', value: '\u22F1' },
  
  // Accents
  '\\hat': { type: 'ESymbol', symbolType: 'Accent', value: '\u005E' },
  '\\check': { type: 'ESymbol', symbolType: 'Accent', value: '\u02C7' },
  '\\tilde': { type: 'ESymbol', symbolType: 'Accent', value: '\u007E' },
  '\\acute': { type: 'ESymbol', symbolType: 'Accent', value: '\u00B4' },
  '\\grave': { type: 'ESymbol', symbolType: 'Accent', value: '\u0060' },
  '\\dot': { type: 'ESymbol', symbolType: 'Accent', value: '\u02D9' },
  '\\ddot': { type: 'ESymbol', symbolType: 'Accent', value: '\u00A8' },
  '\\breve': { type: 'ESymbol', symbolType: 'Accent', value: '\u02D8' },
  '\\bar': { type: 'ESymbol', symbolType: 'Accent', value: '\u00AF' },
  '\\vec': { type: 'ESymbol', symbolType: 'Accent', value: '\u20D7' },
  '\\widehat': { type: 'ESymbol', symbolType: 'Accent', value: '\u0302' },
  '\\widetilde': { type: 'ESymbol', symbolType: 'Accent', value: '\u0303' },
  '\\overline': { type: 'ESymbol', symbolType: 'TOver', value: '\u00AF' },
  '\\underline': { type: 'ESymbol', symbolType: 'TUnder', value: '_' },
  '\\overbrace': { type: 'ESymbol', symbolType: 'TOver', value: '\u23DE' },
  '\\underbrace': { type: 'ESymbol', symbolType: 'TUnder', value: '\u23DF' },
};
